-- MySQL Script generated by MySQL Workbench
-- Thu Sep  3 13:39:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema VENTAS2015
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema VENTAS2015
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VENTAS2015` DEFAULT CHARACTER SET utf8 ;
USE `VENTAS2015` ;

-- -----------------------------------------------------
-- Table `VENTAS2015`.`distro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VENTAS2015`.`distro` (
  `ID_DISTRO` CHAR(3) NOT NULL,
  `DESCRIPCION` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_DISTRO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VENTAS2015`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VENTAS2015`.`cliente` (
  `ID_CLIENTE` CHAR(5) NOT NULL,
  `NOMBRES` VARCHAR(30) NOT NULL,
  `PATERNO` VARCHAR(30) NOT NULL,
  `MATERNO` VARCHAR(30) NOT NULL,
  `DIRECCION` VARCHAR(40) NULL,
  `FONO` VARCHAR(15) NULL,
  `ID_DISTRO` CHAR(3) NOT NULL,
  `EMAIL` VARCHAR(50) NULL,
  PRIMARY KEY (`ID_CLIENTE`),
  INDEX `fk_cliente_distro_idx` (`ID_DISTRO` ASC),
  CONSTRAINT `fk_cliente_distro`
    FOREIGN KEY (`ID_DISTRO`)
    REFERENCES `VENTAS2015`.`distro` (`ID_DISTRO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VENTAS2015`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VENTAS2015`.`producto` (
  `ID_PRODUCTO` CHAR(5) NOT NULL,
  `DESCRIPCION` VARCHAR(50) NOT NULL,
  `PRECIO` DECIMAL(8,2) NOT NULL,
  `STOCK` INT(11) NOT NULL,
  `FACHE_VENC` DATE NULL,
  PRIMARY KEY (`ID_PRODUCTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VENTAS2015`.`boleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VENTAS2015`.`boleta` (
  `NUM_BOLETA` INT(11) NOT NULL AUTO_INCREMENT,
  `FECHA` DATE NOT NULL,
  `ID_CLIENTE` CHAR(5) NOT NULL,
  PRIMARY KEY (`NUM_BOLETA`),
  INDEX `fk_boleta_cliente1_idx` (`ID_CLIENTE` ASC),
  CONSTRAINT `fk_boleta_cliente1`
    FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `VENTAS2015`.`cliente` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VENTAS2015`.`detalleboleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VENTAS2015`.`detalleboleta` (
  `NUM_BOLETA` INT(11) NOT NULL,
  `ID_PRODUCTO` CHAR(5) NOT NULL,
  `CANTIDAD` INT(11) NOT NULL,
  PRIMARY KEY (`NUM_BOLETA`, `ID_PRODUCTO`),
  INDEX `fk_boleta_has_producto_producto1_idx` (`ID_PRODUCTO` ASC),
  INDEX `fk_boleta_has_producto_boleta1_idx` (`NUM_BOLETA` ASC),
  CONSTRAINT `fk_boleta_has_producto_boleta1`
    FOREIGN KEY (`NUM_BOLETA`)
    REFERENCES `VENTAS2015`.`boleta` (`NUM_BOLETA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boleta_has_producto_producto1`
    FOREIGN KEY (`ID_PRODUCTO`)
    REFERENCES `VENTAS2015`.`producto` (`ID_PRODUCTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
